[profile.default]
# no_storage_caching = true
block_gas_limit = 10000000000
# optimizer_runs=100
# optimizer=true
# via_ir = true
eth_rpc_url = "https://api.hyperspace.node.glif.io/rpc/v1"
etherscan_api_key = "R4KES38MISPYEICIJFKEXWDK9H1ZN26I98"
gas_limit = "18446744073709551615"
# [profile.default.optimizer_details]
# constantOptimizer = true
# yul = false
# See more config options https://github.com/foundry-rs/foundry/tree/master/config