name: NPM Audit

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    name: NPM Audit
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: NPM Audit
        run: |
          npm install -g npm-audit-resolver
          check-audit --omit dev --audit-level critical