# .github/workflows/prettier.yml

name: Prettier

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Prettier and Prettier Solidity Plugin
        run: npm install --save-dev prettier prettier-plugin-solidity
      - name: Run Prettier on JavaScript/TypeScript/JSON/CSS/MD
        run: npx prettier --write '**/*.{js,jsx,ts,tsx,json,css,md}'
      - name: Run Prettier on Solidity Files
        run: npx prettier --write '**/*.sol'
      - name: Debugging - Show changed files
        run: git status && git diff --name-only
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier formatting
          branch: ${{ github.head_ref }}
          file_pattern: ./**/*.{js,jsx,ts,tsx,json,css,md,sol}

