name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install abi
        run: pip install eth_abi

      - name: Install lcov and genhtml
        run:  sudo apt-get update && sudo apt-get -y install lcov

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          cache: false

      - name: Run coverage check
        run: make coverage

      - name: Run tests
        run: forge test -vvv --ffi

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Create binding
        run: make compile-abi && make rust-binding && cargo fmt --manifest-path ./binding/Cargo.toml

      - name: Commit bindings
        run: |
          git config --global user.name 'auto-commit'
          git config --global user.email 'auto-commit@users.noreply.github.com'
          make commit-rust-binding
          
